version: '3'

services:
  compute-agents1:
    image: ai.beyond.compute-cluster:0.0.1
    hostname: compute-agents1
    ports:
      - '5050:5050'
    environment:
      HTTP.PORT: 5050
      AKKA.HOST: compute-agents1
      AKKA.PORT: 2550
      AKKA.SEED.HOST: compute-agents1
      AKKA.SEED.PORT: 2550
      KAFKA.SERVERS: "kafka-1:19092,kafka-2:29092,kafka-3:39092"
    volumes:
      - ./logs/compute_agents1:/logs/compute-cluster

  compute-agents2:
    image: ai.beyond.compute-cluster:0.0.1
    hostname: compute-agents2
    ports:
      - '5051:5051'
    depends_on:
      - compute-agents1
    environment:
      HTTP.PORT: 5051
      AKKA.HOST: compute-agents2
      AKKA.PORT: 2551
      AKKA.SEED.HOST: compute-agents1
      AKKA.SEED.PORT: 2550
      KAFKA.SERVERS: "kafka-1:19092,kafka-2:29092,kafka-3:39092"
    volumes:
      - ./logs/compute_agents2:/logs/compute-cluster

  compute-agents3:
    image: ai.beyond.compute-cluster:0.0.1
    hostname: compute-agents3
    ports:
      - '5052:5052'
    depends_on:
      - compute-agents1
    environment:
      HTTP.PORT: 5052
      AKKA.HOST: compute-agents3
      AKKA.PORT: 2552
      AKKA.SEED.HOST: compute-agents1
      AKKA.SEED.PORT: 2550
      KAFKA.SERVERS: "kafka-1:19092,kafka-2:29092,kafka-3:39092"
    volumes:
      - ./logs/compute_agents3:/logs/compute-cluster